language: node_js
node_js:
  - 10

sudo: false
dist: trusty

cache:
  yarn: true

stages:
  - name: 'Deploy'
    if: branch = master AND type = push

jobs:
  include:
    - stage: 'Deploy'
      name: 'Publish to npm'
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash
        - export PATH=$HOME/.yarn/bin:$PATH
      install:
        - yarn install --non-interactive
      script: yarn semantic-release
